language: ruby
rvm:
- 2.2

before_script:
 - chmod +x travis.sh
 - gem install awesome_bot

script: 
 - ./travis.sh
 - awesome_bot ./*/*.md

notifications:
    email: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master
