source 'https://rubygems.org'

gem 'github-pages'
gem 'jekyll-feed'
gem 'rake', '12.0.0'
gem 'rouge'
gem 'pygments.rb'
gem 'jekyll'
gem 'html-proofer'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
